# -*- coding: utf-8 -*-
"""diffusionModel_notebook.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/18A0kwxJZ5N2lCEb4Nm87UaYmj1ldWwrE
"""

!pip install pytorch-fid

"""Setup"""

# Import necessary libraries and configure environment
import torch
import torch.nn as nn
import torch.optim as optim
from torchvision import datasets, transforms

# Set random seed for reproducibility and determine compute device
random_seed = 42
torch.manual_seed(random_seed)
device = 'cuda' if torch.cuda.is_available() else 'cpu'

"""Data Loading"""

# Prepare the MNIST dataset with proper transformations
transform = transforms.Compose([
    transforms.ToTensor(),
    transforms.Normalize((0.5,), (0.5,))  # scale pixel values to [-1, 1]
])
train_data = datasets.MNIST(root='data', train=True, download=True, transform=transform)
train_loader = torch.utils.data.DataLoader(train_data, batch_size=64, shuffle=True)

"""<h1>Model</h1>
Define the model architecture and diffusion process components. We use a simple U-Net–like convolutional network to predict noise, and a diffusion class to handle the noise schedule and algorithms.
"""

# Neural network for denoising (U-Net style, greatly simplified for MNIST)
class DenoiseNet(nn.Module):
    def __init__(self, input_channels=2, base_channels=64):
        super(DenoiseNet, self).__init__()
        # Downsampling layers
        self.conv1 = nn.Conv2d(input_channels, base_channels, kernel_size=3, padding=1)      # Output: 28x28x64
        self.conv2 = nn.Conv2d(base_channels, base_channels*2, kernel_size=4, stride=2, padding=1)  # 14x14x128
        self.conv3 = nn.Conv2d(base_channels*2, base_channels*4, kernel_size=4, stride=2, padding=1) # 7x7x256
        # Upsampling layers
        self.deconv1 = nn.ConvTranspose2d(base_channels*4, base_channels*2, kernel_size=4, stride=2, padding=1)  # 14x14x128
        self.deconv2 = nn.ConvTranspose2d(base_channels*2, base_channels, kernel_size=4, stride=2, padding=1)    # 28x28x64
        self.conv_out = nn.Conv2d(base_channels, 1, kernel_size=3, padding=1)  # Output: 28x28x1 (predicted noise)
    def forward(self, x):
        # Downward pass with ReLU activations
        d1 = torch.relu(self.conv1(x))
        d2 = torch.relu(self.conv2(d1))
        d3 = torch.relu(self.conv3(d2))
        # Upward pass with skip connections
        u1 = torch.relu(self.deconv1(d3))
        u1 = u1 + d2  # add skip connection from downsample 2
        u2 = torch.relu(self.deconv2(u1))
        u2 = u2 + d1  # add skip connection from downsample 1
        return self.conv_out(u2)

# Diffusion process class: defines noise schedule, loss computation, and sampling
class DiffuseNet:
    def __init__(self, model, num_steps=1000, beta_start=1e-4, beta_end=0.02):
        self.model = model.to(device)
        self.num_steps = num_steps
        # Define linear beta schedule β₀...β_{T-1}
        self.beta_schedule = torch.linspace(beta_start, beta_end, num_steps).to(device)
        self.alpha = 1.0 - self.beta_schedule  # α_t = 1 - β_t
        self.alpha_prod = torch.cumprod(self.alpha, dim=0)  # cumulative product ∏_{s=0}^{t} α_s
        # Pre-calculate often-used terms for efficiency
        self.sqrt_alpha_prod = torch.sqrt(self.alpha_prod)
        self.sqrt_one_minus_alpha_prod = torch.sqrt(1 - self.alpha_prod)

    def compute_loss(self, x0):
        """Compute training loss on a batch of real images x0."""
        batch_size = x0.size(0)
        # Sample a random diffusion step for each image in the batch
        t = torch.randint(0, self.num_steps, (batch_size,), device=device)
        # Sample standard normal noise
        noise = torch.randn_like(x0)
        # Retrieve corresponding alpha_t terms
        alpha_prod_t = self.alpha_prod[t].view(-1, 1, 1, 1)
        sqrt_alpha_prod_t = self.sqrt_alpha_prod[t].view(-1, 1, 1, 1)
        sqrt_one_minus_alpha_prod_t = self.sqrt_one_minus_alpha_prod[t].view(-1, 1, 1, 1)
        # Diffuse the images by adding noise at step t
        x_t = sqrt_alpha_prod_t * x0 + sqrt_one_minus_alpha_prod_t * noise  # noisy image at time t
        # Prepare time as an additional input channel (normalized to [0,1])
        t_norm = t.float() / self.num_steps
        t_channel = t_norm.view(-1, 1, 1, 1).repeat(1, 1, x0.shape[2], x0.shape[3])
        # Predict noise using the model
        pred_noise = self.model(torch.cat([x_t, t_channel], dim=1))
        # Return mean squared error between actual noise and predicted noise
        return torch.mean((noise - pred_noise) ** 2)

    def generate_images(self, num_samples):
        """Generate new images by iteratively removing noise."""
        self.model.eval()  # switch model to evaluation mode
        x = torch.randn(num_samples, 1, 28, 28, device=device)  # start from pure noise
        for t in reversed(range(self.num_steps)):
            # Prepare time channel for current step
            t_tensor = torch.full((num_samples,), t, device=device, dtype=torch.long)
            t_channel = (t_tensor.float() / self.num_steps).view(-1, 1, 1, 1).repeat(1, 1, x.shape[2], x.shape[3])
            # Predict noise at time t
            pred_noise = self.model(torch.cat([x, t_channel], dim=1))
            # Compute the estimated previous step x_{t-1} (predicted mean of the distribution)
            beta_t = self.beta_schedule[t]
            alpha_t = 1.0 - beta_t
            alpha_prod_t = self.alpha_prod[t]
            # μ_t = 1/√α_t * (x_t - (1−α_t)/√(1−α_prod_t) * pred_noise)
            x_prev_mean = (1 / alpha_t.sqrt()) * (x - (1 - alpha_t) / (1 - alpha_prod_t).sqrt() * pred_noise)
            if t > 0:
                # Add random noise for t > 0: x_{t-1} = μ_t + σ_t * z, with σ_t = √β_t
                z = torch.randn_like(x)
                x = x_prev_mean + beta_t.sqrt() * z
            else:
                # At last step, use mean without additional noise
                x = x_prev_mean
        return x  # shape: [num_samples, 1, 28, 28] tensor of generated images

"""<h1>Training"""

# Initialize the model and diffusion process
denoise_model = DenoiseNet()
diffusion = DiffuseNet(model=denoise_model, num_steps=1000)
optimizer = optim.Adam(diffusion.model.parameters(), lr=1e-3)

# Train the model over multiple epochs
epochs = 15
for epoch in range(1, epochs+1):
    for real_imgs, _ in train_loader:
        real_imgs = real_imgs.to(device)
        optimizer.zero_grad()
        loss = diffusion.compute_loss(real_imgs)
        loss.backward()
        optimizer.step()
    print(f"Epoch {epoch}/{epochs} - Loss: {loss.item():.4f}")

"""Let's plot it to be better see how did the process go!"""

import matplotlib.pyplot as plt

# Loss values for each epoch
loss_data = [0.0450, 0.0457, 0.0344, 0.0333, 0.0279, 0.0331, 0.0282, 0.0294, 0.0242, 0.0261, 0.0205, 0.0307, 0.0425, 0.0206, 0.0226]
epochs = list(range(1, 16))

# Create the plot
plt.figure(figsize=(6, 4))
plt.plot(epochs, loss_data, marker='o', color='b', linewidth=2)
plt.title("Training Loss over Epochs")
plt.xlabel("Epochs")
plt.ylabel("Loss")
plt.xticks(epochs)
plt.grid(True)
plt.show()

"""<h1>Sampling"""

# Use the trained model to generate new digit images
num_samples = 16
generated_images = diffusion.generate_images(num_samples)
# Rescale generated images back to [0,1] for viewing
generated_images = (generated_images * 0.5 + 0.5).clamp(0, 1)

import matplotlib.pyplot as plt

# Plot a grid of generated sample images
fig, axes = plt.subplots(4, 4, figsize=(6, 6))
for i, ax in enumerate(axes.flatten()):
    ax.axis('off')
    ax.imshow(generated_images[i, 0].cpu().detach().numpy(), cmap='gray')
plt.tight_layout()
plt.show()

"""This cell computes evaluation metrics for the generated images:
<ol>
<li>Preprocessing:</li>

Denormalizes generated and real MNIST images from [-1, 1] to [0, 1].

<li>Compute MSE & PSNR:

Calculates Mean Squared Error (MSE) and Peak Signal-to-Noise Ratio (PSNR) between real and generated images.

<li>Save Images for FID:

Saves real and generated images to disk for FID calculation.

<li>Compute FID:

Calculates Fréchet Inception Distance (FID) between the real and generated images.
</ol>

These metrics evaluate the quality and similarity of the generated images to the real MNIST dataset.









"""

